{
 "title": "Era - general",
 "tags": [ "Era-Main" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(server_processed_txs{stage=~\"state_keeper\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum by (stage) (rate(server_processed_txs{pod!=\"$exclude_pod\", namespace=~\"$namespace|\", stage=~\"mempool_added\"}[$__rate_interval]))",
     "legendFormat": "TPS",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "L1 Batch Height",
   "type": "timeseries",
   "description": "L1 batch number per stage - from being `sealed` in `state_keeper` to `l1_mined_ExecuteBlocks` in `btc_sender`. Delay in proof l1 operation is commonly observed when there are issues with provers, while a delay in commit operation is indicative of problems with `btc_sender`",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "max by (stage) (server_block_number{namespace=~\"$namespace|\", stage=~\"sealed|wit_gen_BasicCircuits|prove_Scheduler|l1_mined_CommitBlocks|l1_mined_ExecuteBlocks|l1_mined_PublishProofBlocksOnchain\"})\n",
     "legendFormat": "{{stage}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Versions",
   "type": "table",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (iname,ver)(label_replace(label_replace(kube_pod_container_info{namespace='$namespace'},\"ver\",\"$2\",\"image\",\"(.*):(.*)\"),\"iname\",\"$2\",\"image_spec\",\"(.*)/(.*):(.*)\"))",
     "legendFormat": "="
    }
   ]
  },
  {
   "title": "Execution Delay",
   "type": "timeseries",
   "description": "The 24-hour difference between committing a block and executing it On chain.\nIf two lines cross and Execute line below Commit, that means we delayed withdrawals for more  then 24hrs ",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "max by (stage) (server_block_number{namespace=~\"$namespace|\", stage=~\"l1_mined_CommitBlocks|sealed\"} offset 24h)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (stage) (server_block_number{namespace=~\"$namespace|\", stage=~\"l1_mined_ExecuteBlocks|l1_mined_PublishProofBlocksOnchain\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions execution statuses in State Keeper",
   "type": "timeseries",
   "description": "Number of transactions with execution results in State Keeper:\nRejected:\nThey waste the Sequencer resources without paying fee, so high number of them is indicative of a bug or a DoS attack\nReverted:\nSucceeded:",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(server_state_keeper_tx_execution_result{namespace=~\"$namespace|\"}[$__rate_interval])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Priority transactions TPS",
   "type": "timeseries",
   "description": "Number of priority/L1 transactions added and executed per second",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(rate(server_processed_l1_txs{namespace=~\"$namespace|\", stage=~\"state_keeper|mempool_added\"}[$__rate_interval]))",
     "legendFormat": "{{stage}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ETH Balances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "max (eth_balance{service=\"ethexporter-l2\"}) by (name)",
     "legendFormat": "L2-{{name}}"
    },
    {
     "expr": "avg by (name) (eth_balance{namespace=~\"$namespace|\", service=\"ethexporter\"})",
     "legendFormat": "L1-{{name}} "
    }
   ]
  },
  { "title": "External Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "L2 block height per node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "max by (pod) (server_miniblock_number{label!=\"snapshot_recovery_test\"})\n",
     "legendFormat": "{{pod}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EN lag",
   "type": "timeseries",
   "description": "Note that blocks are produced every second, whereas the metrics are scraped every 30 seconds, so some discrepancy is expected. Missing series signify node being down.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "max(server_miniblock_number{pod=\"server-v2-core-0\"}) - max(server_miniblock_number{pod=\"external-node-moby-0\"})",
     "legendFormat": "external-node-moby-0",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "max(server_miniblock_number{pod=\"server-v2-core-0\"}) - max(server_miniblock_number{pod=\"external-node-0\"})",
     "legendFormat": "external-node-0",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  }
 ]
}