{
 "title": "Era - sequencer",
 "description": "Graphs related to the sequencer (also known as the state keeper)",
 "tags": [ "Era-Main" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(server_processed_txs{stage=~\"state_keeper\"},namespace)"
    }
   },
   {
    "name": "state_keeper_seal_l1_batch_stages",
    "query": {
     "query": "label_values(via_server_state_keeper_l1_batch_sealed_time_stage_count, stage)"
    }
   },
   {
    "name": "state_keeper_seal_miniblock_stages",
    "query": {
     "query": "label_values(via_server_state_keeper_miniblock_sealed_time_stage_count, stage)"
    }
   },
   { "name": "aggr", "label": "aggregate by", "query": "$__interval,1h,1d,1w" },
   {
    "name": "pod",
    "query": {
     "query": "label_values(server_processed_txs{stage=~\"state_keeper\",namespace=\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transactions per second",
   "type": "timeseries",
   "description": "Transactions per second: how many are added to mempool and how many are executed in the state keeper. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg_over_time(\n  sum by (pod, stage) (\n    rate(server_processed_txs{pod=~\"$pod|\", namespace=~\"$namespace|\", stage=~\"mempool_added|state_keeper\", label!=\"snapshot_recovery_test\"}[$__rate_interval])\n  )[$aggr:]\n)",
     "legendFormat": "{{stage}}-{{pod}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    },
    {
     "expr": "avg_over_time(sum by (stage) (rate(server_processed_txs{pod=~\"server-v2-api.*|server-v2-ws-api.*\", namespace=~\"$namespace|\", stage=~\"mempool_added\", label!=\"snapshot_recovery_test\"}[$__rate_interval]))[$aggr:])\n",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Waiting for transaction",
   "type": "timeseries",
   "description": "Average - time that state keeper spends waiting for a transaction in mempool. When non-zero - that means that the mempool is empty. When zero - that state keeper is working at highest throughput. The value is capped at one second - if we need to wait more, we start over. That means that if there are no incoming transactions, the graph will show flat line at one second",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (pod) (rate(via_server_state_keeper_waiting_for_tx_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])/rate(via_server_state_keeper_waiting_for_tx_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]))\n\n\n\n\n\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Waiting for Transaction",
   "type": "heatmap",
   "description": "Histogram - time that state keeper spends waiting for a transaction in mempool. When non-zero - that means that the mempool is empty. When zero - that state keeper is working at highest throughput. The value is capped at one second - if we need to wait more, we start over. That means that if there are no incoming transactions, the graph will show flat line at one second",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(rate(via_server_state_keeper_waiting_for_tx_bucket{pod=~\"$pod|\", namespace=~\"$namespace|\"}[$__interval])) by (le)\n",
     "legendFormat": "{{le}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Tx Inclusion wait time (10m aggregation)",
   "type": "timeseries",
   "description": "The time transactions spend in the mempool. More precisely, time delta between a transaction's `received_at` DB field (which is recorded when transaction is first persisted) and the miniblock time the tx is included in.\nThis doesn't include some other time that affects tx submission user experience, like estimate_gas time, submit_raw_tx time, polling time etc.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "histogram_quantile(0.9, sum by(le, pod) (rate(via_server_state_keeper_transaction_inclusion_delay_bucket{namespace=~\"$namespace|\", tx_execution_type=\"l2\"}[10m])))\n",
     "legendFormat": "p90",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "histogram_quantile(0.99, sum by(le, pod) (rate(via_server_state_keeper_transaction_inclusion_delay_bucket{namespace=~\"$namespace|\", tx_execution_type=\"l2\"}[10m])))\n",
     "legendFormat": "p99",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "histogram_quantile(0.5, sum by(le, pod) (rate(via_server_state_keeper_transaction_inclusion_delay_bucket{namespace=~\"$namespace|\", tx_execution_type=\"l2\"}[10m])))\n",
     "legendFormat": "p50",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "histogram_quantile(0.95, sum by(le, pod) (rate(via_server_state_keeper_transaction_inclusion_delay_bucket{namespace=~\"$namespace|\", tx_execution_type=\"l2\"}[10m])))\n",
     "legendFormat": "p95",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Tx VM + Storage time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg_over_time((avg by (pod, stage) (rate(via_server_state_keeper_tx_execution_time_sum{pod=~\"$pod|\", namespace=~\"$namespace|\"}[$__rate_interval])/rate(via_server_state_keeper_tx_execution_time_count{pod=~\"$pod|\", namespace=~\"$namespace|\"}[$__rate_interval])))[$aggr:])\n\n\n\n\n\n\n",
     "legendFormat": "{{pod}}-{{stage}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Frequency of Tx rollback",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "rate(via_server_state_keeper_tx_execution_time_count{pod=~\"$pod|\", namespace=~\"$namespace|\", stage=\"tx_rollback\"}[$__rate_interval])\n\n\n\n\n\n",
     "legendFormat": "{{stage}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Tx Inclusion wait time",
   "type": "heatmap",
   "description": "The time transactions spend in the mempool. More precisely, time delta between a transaction's `received_at` DB field (which is recorded when transaction is first persisted) and the miniblock time the tx is included in.\nThis doesn't include some other time that affects tx submission user experience, like estimate_gas time, submit_raw_tx time, polling time etc.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(increase(via_server_state_keeper_transaction_inclusion_delay_bucket{namespace=~\"$namespace|\", tx_execution_type=\"l2\"}[30s])) by (le)\n",
     "legendFormat": "{{le}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VM + storage per tx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, pod) (rate(via_server_state_keeper_tx_execution_time_bucket{pod=~\"$pod|\",namespace=~\"$namespace|\"}[$__rate_interval])))",
     "legendFormat": "0.95-{{pod}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, pod) (rate(via_server_state_keeper_tx_execution_time_bucket{pod=~\"$pod|\",namespace=~\"$namespace|\"}[$__rate_interval])))",
     "legendFormat": "0.5-{{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, pod) (rate (via_server_state_keeper_tx_execution_time_bucket{pod=~\"$pod|\",namespace=~\"$namespace|\"}[$__rate_interval])))",
     "legendFormat": "0.99-{{pod}}"
    },
    {
     "expr": "sum by (pod) (rate(via_server_state_keeper_tx_execution_time_sum{pod=~\"$pod|\",namespace=~\"$namespace|\"}[$__rate_interval]) / rate(via_server_state_keeper_tx_execution_time_count{pod=~\"$pod|\",namespace=~\"$namespace|\"}[$__rate_interval]))",
     "legendFormat": "average-{{pod}}"
    }
   ]
  },
  {
   "title": "Tx Execution Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(rate(via_server_state_keeper_tx_execution_time_bucket{pod=~\"$pod|\", namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__interval])) by (le)\n",
     "legendFormat": "{{le}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Transactions rejected in State Keeper",
   "type": "timeseries",
   "description": "Number of transactions rejected in State Keeper. They waste the Sequencer resources without paying fee, so high number of them is indicative of a bug or a DoS attack",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(via_server_state_keeper_rejected_transactions{namespace=~\"$namespace|\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Launch time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(server_init_latency{namespace=~\"$namespace|\", stage=\"state_keeper\", pod=~\"$pod|\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Miniblock sealing - $pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 }, "repeat": "pod" },
  {
   "title": "Miniblock Interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, pod) (rate(via_server_state_keeper_miniblock_seal_delta_bucket{pod=~\"$pod|\",namespace=~\"$namespace|\"}[$__rate_interval])))",
     "legendFormat": "0.95-{{pod}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, pod) (rate(via_server_state_keeper_miniblock_seal_delta_bucket{pod=~\"$pod|\",namespace=~\"$namespace|\"}[$__rate_interval])))",
     "legendFormat": "0.5-{{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, pod) (rate (via_server_state_keeper_miniblock_seal_delta_bucket{pod=~\"$pod|\",namespace=~\"$namespace|\"}[$__rate_interval])))",
     "legendFormat": "0.99-{{pod}}"
    },
    {
     "expr": "rate(via_server_state_keeper_miniblock_seal_delta_sum{pod=~\"$pod|\",namespace=~\"$namespace|\"}[$__rate_interval]) / rate(via_server_state_keeper_miniblock_seal_delta_count{pod=~\"$pod|\",namespace=~\"$namespace|\"}[$__rate_interval])",
     "legendFormat": "average-{{pod}}"
    }
   ]
  },
  {
   "title": "Miniblock Interval",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(via_server_state_keeper_miniblock_seal_delta_bucket{namespace=~\"$namespace|\",pod=~\"$pod|\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Miniblock Seal Stages Time",
   "type": "timeseries",
   "description": "Sealing miniblock consist of multiple stages - this graph shows how much each stage impact the total time it takes to seal a miniblock",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 34 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum by (stage) (rate(via_server_state_keeper_miniblock_sealed_time_stage_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]) / rate(via_server_state_keeper_miniblock_sealed_time_stage_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]))",
     "legendFormat": "{{stage}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Miniblock Seal Stages Time",
   "type": "timeseries",
   "description": "Sealing miniblock consist of multiple stages - this graph shows how much each stage impact the total time it takes to seal a miniblock",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum by (stage) (rate(via_server_state_keeper_miniblock_sealed_time_stage_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]) / rate(via_server_state_keeper_miniblock_sealed_time_stage_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]))",
     "legendFormat": "{{stage}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Miniblock seal queue capacity",
   "type": "timeseries",
   "description": "Available capacity of miniblock seal queue",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (pod) (via_server_state_keeper_miniblock_seal_queue_capacity{namespace=\"$namespace\", pod=~\"$pod|\"})",
     "legendFormat": "Capacity-{{pod}}"
    }
   ]
  },
  {
   "title": "Miniblock seal queue latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (pod) (rate(via_server_state_keeper_miniblock_seal_queue_latency_sum{namespace=\"$namespace\", pod=~\"$pod|\", stage=\"submit\"}[$__rate_interval])/rate(via_server_state_keeper_miniblock_seal_queue_latency_count{namespace=\"$namespace\", pod=~\"$pod|\", stage=\"submit\"}[$__rate_interval]))",
     "legendFormat": "Submit-{{pod}}"
    },
    {
     "expr": "max by (pod) (rate(via_server_state_keeper_miniblock_seal_queue_latency_sum{namespace=\"$namespace\", pod=~\"$pod|\", stage=\"wait_for_all_commands\"}[$__rate_interval])/rate(via_server_state_keeper_miniblock_seal_queue_latency_count{namespace=\"$namespace\", pod=~\"$pod|\", stage=\"wait_for_all_commands\"}[$__rate_interval]))",
     "legendFormat": "Wait for all commands-{{pod}}"
    },
    {
     "expr": "max by (pod) (rate(via_server_state_keeper_miniblock_seal_queue_latency_sum{namespace=\"$namespace\", pod=~\"$pod|\", stage=\"next_command\"}[$__rate_interval])/rate(via_server_state_keeper_miniblock_seal_queue_latency_count{namespace=\"$namespace\", pod=~\"$pod|\", stage=\"next_command\"}[$__rate_interval]))",
     "legendFormat": "Next command-{{pod}}"
    }
   ]
  },
  {
   "title": "Seal Miniblock DB Time - average",
   "type": "timeseries",
   "description": "Average time it takes to save the miniblock in Postgres. See \"miniblock stage ... \" rows below",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg_over_time (avg by(pod) (rate(via_server_state_keeper_miniblock_sealed_time_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])/rate(via_server_state_keeper_miniblock_sealed_time_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]))[$aggr:])\n\n\n\n\n\n\n",
     "legendFormat": "{{pod}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Seal Miniblock DB Time",
   "type": "heatmap",
   "description": "Histogram of the time it takes to seal a miniblock and its data - mostly DB time. See \"miniblock stage ... \" rows below.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 42 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(rate(via_server_state_keeper_miniblock_sealed_time_bucket{namespace=~\"$namespace|\",pod=~\"$pod|\"}[$__rate_interval])) by (le)\n",
     "legendFormat": "{{le}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Txs Per Miniblock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg_over_time((rate(via_server_state_keeper_miniblock_transactions_in_miniblock_sum{pod=~\"$pod|\", namespace=~\"$namespace|\"}[$__rate_interval])/rate(via_server_state_keeper_miniblock_transactions_in_miniblock_count{pod=~\"$pod|\", namespace=~\"$namespace|\"}[$__rate_interval]))[$aggr:])\n",
     "legendFormat": "average-{{pod}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "max(via_server_state_keeper_miniblock_transactions_in_miniblock{pod=~\"$pod|\", namespace=~\"$namespace|\", quantile=\"1\"})",
     "legendFormat": "max",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "max(via_server_state_keeper_miniblock_transactions_in_miniblock{pod=~\"$pod|\", namespace=~\"$namespace|\", quantile=\"0.95\"})",
     "legendFormat": "95p",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "min(via_server_state_keeper_miniblock_transactions_in_miniblock{pod=~\"$pod|\", namespace=~\"$namespace|\", quantile=\"0\"})",
     "legendFormat": "min",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg(via_server_state_keeper_miniblock_transactions_in_miniblock{pod=~\"$pod|\", namespace=~\"$namespace|\", quantile=\"0.5\"})",
     "legendFormat": "median",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "[WIP] Seal Miniblock Time per transaction",
   "type": "timeseries",
   "description": "Average time it takes to save the miniblock divided by the number of txs in it.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg(rate(via_server_state_keeper_miniblock_sealed_time_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])/rate(via_server_state_keeper_miniblock_sealed_time_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]))/(rate(via_server_state_keeper_miniblock_transactions_in_miniblock_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])/rate(via_server_state_keeper_miniblock_transactions_in_miniblock_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]))\n\n\n\n\n\n\n",
     "legendFormat": "{{pod}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "L2 Block Seal Reason",
   "type": "timeseries",
   "description": "This graph shows why we seal l2 blocks",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 50 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum by (reason) (rate(server_tx_aggregation_l2_block_reason{namespace=~\"$namespace|\"}[$__rate_interval]))",
     "legendFormat": "{{reason}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Wait for l2 block parameters: time",
   "type": "timeseries",
   "description": "Time spent on waiting for new l2 block parameters",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg_over_time((avg by (pod, stage) (rate(via_server_state_keeper_wait_for_l2_block_params_sum{pod=~\"$pod|\", namespace=~\"$namespace|\"}[$__rate_interval])/rate(via_server_state_keeper_wait_for_l2_block_params_count{pod=~\"$pod|\", namespace=~\"$namespace|\"}[$__rate_interval])))[$aggr:])\n\n\n\n\n\n\n",
     "legendFormat": "{{pod}}-{{stage}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "L1 batch sealing - $pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 }, "repeat": "pod" },
  {
   "title": "L1 batch Seal Stages Time - scaled",
   "type": "timeseries",
   "description": "Sealing L1 batch consist of multiple stages - this graph shows how much each stage impact the total time it takes to seal a batch",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 67 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum by (stage) (increase(via_server_state_keeper_l1_batch_sealed_time_stage_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]) / increase(via_server_state_keeper_l1_batch_sealed_time_stage_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]))",
     "legendFormat": "{{stage}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    },
    {
     "expr": "sum by (stage) (increase(via_server_state_keeper_wait_for_prev_hash_time_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]) / increase(via_server_state_keeper_wait_for_prev_hash_time_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]))",
     "legendFormat": "waiting_for_tree"
    }
   ]
  },
  {
   "title": "L1 batch Seal Stages Time - absolute",
   "type": "timeseries",
   "description": "Sealing L1 batch consist of multiple stages - this graph shows how much each stage impact the total time it takes to seal a batch",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum by (stage) (increase(via_server_state_keeper_l1_batch_sealed_time_stage_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]) / increase(via_server_state_keeper_l1_batch_sealed_time_stage_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]))",
     "legendFormat": "{{stage}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    },
    {
     "expr": "sum by (stage) (increase(via_server_state_keeper_wait_for_prev_hash_time_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]) / increase(via_server_state_keeper_wait_for_prev_hash_time_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]))",
     "legendFormat": "waiting_for_tree"
    }
   ]
  },
  {
   "title": "L1 batch Seal Reason",
   "type": "timeseries",
   "description": "There are multiple reasons why we'd want to seal l1 batch - this graph shows how often and why we seal l1 batches",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 75 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum by (criterion) (rate(server_tx_aggregation_reason{namespace=~\"$namespace|\"}[$__rate_interval]))",
     "legendFormat": "{{criterion}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Txs Per L1 Batch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg by (pod) (rate(via_server_state_keeper_l1_batch_transactions_in_l1_batch_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])/rate(via_server_state_keeper_l1_batch_transactions_in_l1_batch_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]))",
     "legendFormat": "average-{{pod}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "max(via_server_state_keeper_l1_batch_transactions_in_l1_batch{pod=~\"$pod|\", namespace=~\"$namespace|\", quantile=\"1\"})",
     "legendFormat": "max",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "max(via_server_state_keeper_l1_batch_transactions_in_l1_batch{pod=~\"$pod|\", namespace=~\"$namespace|\", quantile=\"0.95\"})",
     "legendFormat": "95p",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "min(via_server_state_keeper_l1_batch_transactions_in_l1_batch{pod=~\"$pod|\", namespace=~\"$namespace|\", quantile=\"0\"})",
     "legendFormat": "min",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg(via_server_state_keeper_l1_batch_transactions_in_l1_batch{pod=~\"$pod|\", namespace=~\"$namespace|\", quantile=\"0.5\"})",
     "legendFormat": "median",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Waiting for Tree",
   "type": "timeseries",
   "description": "Time passed while state keeper is waiting for the tree to compute the previous block root hash - it's needed to start the execution of the next l1 batch",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "rate(via_server_state_keeper_wait_for_prev_hash_time_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])/rate(via_server_state_keeper_wait_for_prev_hash_time_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])\n\n\n\n\n\n\n",
     "legendFormat": "{{pod}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "L1 batch Seal Time",
   "type": "timeseries",
   "description": "Time it takes to seal an l1 batch and its data - mostly DB time. See \"l1 batch stage ... \" rows below.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg_over_time(avg by (pod) (rate(via_server_state_keeper_l1_batch_sealed_time_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])/rate(via_server_state_keeper_l1_batch_sealed_time_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]))[$aggr:])\n\n\n\n\n\n\n",
     "legendFormat": "{{pod}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "L1 Batch Interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(avg by (pod) (rate(via_server_state_keeper_l1_batch_seal_delta_sum{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]) / rate(via_server_state_keeper_l1_batch_seal_delta_count{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval]))[$aggr:])",
     "legendFormat": "average-{{pod}}"
    },
    {
     "expr": "avg_over_time(histogram_quantile(0.5, sum by(pod, le) (rate(via_server_state_keeper_l1_batch_seal_delta_bucket{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])))[$aggr:])",
     "legendFormat": "0.5-{{pod}}"
    },
    {
     "expr": "avg_over_time(histogram_quantile(0.99, sum by(pod, le) (rate(via_server_state_keeper_l1_batch_seal_delta_bucket{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])))[$aggr:])",
     "legendFormat": "0.99-{{pod}}"
    },
    {
     "expr": "avg_over_time(histogram_quantile(0.95, sum by(pod, le) (rate(via_server_state_keeper_l1_batch_seal_delta_bucket{namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])))[$aggr:])",
     "legendFormat": "0.95-{{pod}}"
    }
   ]
  },
  {
   "title": "L1 batch Interval",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 83 },
   "targets": [
    {
     "expr": "sum(rate(via_server_state_keeper_l1_batch_seal_delta_bucket{namespace=~\"$namespace|\",pod=~\"$pod|\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Mempool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "collapsed": true,
   "panels": [
    {
     "title": "mempool sync with db latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 92 },
     "targets": [
      {
       "expr": "sum(rate(via_server_state_keeper_mempool_sync_bucket{namespace=~\"$namespace|\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "mempool sync with db latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(rate(via_server_state_keeper_mempool_sync_sum{namespace=~\"$namespace|\"}[$__rate_interval])/rate(via_server_state_keeper_mempool_sync_count{namespace=~\"$namespace|\"}[$__rate_interval]))\n\n\n\n\n\n\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Get Tx From Mempool",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 92 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum(rate(via_server_state_keeper_get_tx_from_mempool_bucket{namespace=~\"$namespace|\"}[$__rate_interval])) by (le)\n",
       "legendFormat": "{{le}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "mempool size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 92 },
     "targets": [
      {
       "expr": "sum(via_server_state_keeper_mempool_l2_size{pod!=\"$exclude_pod\", namespace=~\"$namespace|\"})",
       "legendFormat": "l2_txs (including the ones with nonce gaps)"
      },
      {
       "expr": "sum(via_server_state_keeper_mempool_l1_size{pod!=\"$exclude_pod\", namespace=~\"$namespace|\"})\n",
       "legendFormat": "l1_txs"
      },
      {
       "expr": "sum(via_server_state_keeper_mempool_l2_priority_queue_size{pod!=\"$exclude_pod\", namespace=~\"$namespace|\"})\n",
       "legendFormat": "accounts_with_ready_txs"
      }
     ]
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "State Keeper Cache Lag",
   "type": "timeseries",
   "description": "Difference between the latest block in RocksDB cache and Postgres",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "Blocks" } },
   "targets": [
    {
     "expr": "max by (pod) (server_state_keeper_secondary_storage_lag { pod=~\"$pod|\", namespace=~\"$namespace|\" })",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Live data size",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (cf) (rocksdb_live_data_size{pod=\"$pod\", namespace=\"$namespace\", db=\"state_keeper\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total SST size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (cf) (rocksdb_total_sst_size{pod=\"$pod\", namespace=\"$namespace\", db=\"state_keeper\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index + Bloom filter size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (cf) (rocksdb_index_and_filters_size{pod=\"$pod\", namespace=\"$namespace\", db=\"state_keeper\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block cache size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (db) (rocksdb_block_cache_size{pod=\"$pod\", namespace=\"$namespace\", db=\"state_keeper\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SST files by level – state CF",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (level) (rocksdb_files_at_level{pod=\"$pod\", namespace=\"$namespace\", db=\"state_keeper\", cf=\"state\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Memory usage (RSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (pod) (container_memory_rss{container_name=~\"server-v2-core.*|external-node.*\", namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage (working set)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (pod) (container_memory_working_set_bytes{container_name=~\"server-v2-core.*|external-node.*\", namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage (page cache)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (pod) (container_memory_cache{container_name=~\"server-v2-core.*|external-node.*\", namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Miniblock seal stage $state_keeper_seal_miniblock_stages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 },
   "repeat": "state_keeper_seal_miniblock_stages",
   "collapsed": true,
   "panels": [
    {
     "title": "total time - average",
     "type": "timeseries",
     "description": "Time spent on $state_keeper_seal_miniblock_stages miniblock seal stage",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "avg_over_time(avg by (pod) (rate(via_server_state_keeper_miniblock_sealed_time_stage_sum{stage=\"$state_keeper_seal_miniblock_stages\", namespace=~\"$namespace|\", pod=~\"$pod|\", is_fictive=~\"false|\"}[$__rate_interval])/rate(via_server_state_keeper_miniblock_sealed_time_stage_count{stage=\"$state_keeper_seal_miniblock_stages\", namespace=~\"$namespace|\", pod=~\"$pod|\", is_fictive=~\"false|\"}[$__rate_interval]))[$aggr:])\n\n",
       "legendFormat": "{{pod}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "per entity/row - average",
     "type": "timeseries",
     "description": "Time spent on $state_keeper_seal_miniblock_stages miniblock seal stage",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "avg_over_time(avg by (pod) (rate(via_server_state_keeper_miniblock_sealed_entity_per_unit_sum{stage=\"$state_keeper_seal_miniblock_stages\", namespace=~\"$namespace|\", pod=~\"$pod|\", is_fictive=~\"false|\"}[$__rate_interval])/rate(via_server_state_keeper_miniblock_sealed_entity_per_unit_count{stage=\"$state_keeper_seal_miniblock_stages\", namespace=~\"$namespace|\", pod=~\"$pod|\", is_fictive=~\"false|\"}[$__rate_interval]))[$aggr:])\n\n",
       "legendFormat": "{{pod}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "number of entities/rows - average",
     "type": "timeseries",
     "description": "Average number of resulting/affected DB rows/entities from $state_keeper_seal_miniblock_stages when saving miniblock execution result.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "avg_over_time(avg by (pod) (rate(via_server_state_keeper_miniblock_sealed_entity_count_sum{stage=\"$state_keeper_seal_miniblock_stages\", namespace=~\"$namespace|\", pod=~\"$pod|\", is_fictive=\"false\"}[$__rate_interval])/rate(via_server_state_keeper_miniblock_sealed_entity_count_count{stage=\"$state_keeper_seal_miniblock_stages\", namespace=~\"$namespace|\", pod=~\"$pod|\", is_fictive=\"false\"}[$__rate_interval]))[$aggr:])\n\n",
       "legendFormat": "{{pod}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "total time - heatmap - $pod",
     "type": "heatmap",
     "description": "Time spent on $state_keeper_seal_miniblock_stages miniblock seal stage",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 109 },
     "repeat": "pod",
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum(rate(via_server_state_keeper_miniblock_sealed_time_stage_bucket{stage=\"$state_keeper_seal_miniblock_stages\", namespace=~\"$namespace|\", pod=~\"$pod|\", is_fictive=\"false\"}[$__rate_interval])) by (le)\n",
       "legendFormat": "{{le}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "per entity/row - heatmap - $pod",
     "type": "heatmap",
     "description": "Histogram of time spent in state keeper on $state_keeper_seal_miniblock_stages when saving miniblock execution result, divided by the number of resulting/affected number DB rows/entities. Doesn't apply for all stages.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 109 },
     "repeat": "pod",
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum(rate(via_server_state_keeper_miniblock_sealed_entity_per_unit_bucket{stage=\"$state_keeper_seal_miniblock_stages\", namespace=~\"$namespace|\", pod=~\"$pod|\", is_fictive=\"false\"}[$__rate_interval])) by (le)\n",
       "legendFormat": "{{le}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "number of entities - heatmap - $pod",
     "type": "heatmap",
     "description": "Histogram of time spent in state keeper on $state_keeper_seal_miniblock_stages when saving miniblock execution result, divided by the number of resulting/affected DB rows/entities. Doesn't apply for all stages.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 109 },
     "repeat": "pod",
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum(rate(via_server_state_keeper_miniblock_sealed_entity_count_bucket{stage=\"$state_keeper_seal_miniblock_stages\", namespace=~\"$namespace|\", pod=~\"$pod|\", is_fictive=\"false\"}[$__rate_interval])) by (le)\n",
       "legendFormat": "{{le}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "L1 batch seal stage $state_keeper_seal_l1_batch_stages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 },
   "repeat": "state_keeper_seal_l1_batch_stages",
   "collapsed": true,
   "panels": [
    {
     "title": "Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 452 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "rate(via_server_state_keeper_l1_batch_sealed_time_stage_sum{stage=\"$state_keeper_seal_l1_batch_stages\", namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])/rate(via_server_state_keeper_l1_batch_sealed_time_stage_count{stage=\"$state_keeper_seal_l1_batch_stages\", namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])\n\n",
       "legendFormat": "{{pod}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Average per row inserted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 452 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "rate(via_server_state_keeper_l1_batch_sealed_entity_per_unit_sum{stage=\"$state_keeper_seal_l1_batch_stages\", namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])/rate(via_server_state_keeper_l1_batch_sealed_entity_per_unit_count{stage=\"$state_keeper_seal_l1_batch_stages\", namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])\n\n",
       "legendFormat": "{{pod}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Counts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 452 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "rate(via_server_state_keeper_l1_batch_sealed_entity_count_sum{stage=\"$state_keeper_seal_l1_batch_stages\", namespace=~\"$namesp ace|\", pod=~\"$pod|\"}[$__rate_interval])/rate(via_server_state_keeper_l1_batch_sealed_entity_count_count{stage=\"$state_keeper_seal_l1_batch_stages\", namespace=~\"$namespace|\", pod=~\"$pod|\"}[$__rate_interval])\n\n",
       "legendFormat": "{{pod}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 138 },
   "collapsed": true,
   "panels": [
    {
     "title": "Updates manager: finish batch",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 741 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "avg_over_time((avg by (pod, stage) (rate(via_server_state_keeper_updates_manager_finish_batch_sum{pod=~\"$pod|\", namespace=~\"$namespace|\"}[$__rate_interval])/rate(via_server_state_keeper_updates_manager_finish_batch_count{pod=~\"$pod|\", namespace=~\"$namespace|\"}[$__rate_interval])))[$aggr:])\n\n\n\n\n\n\n",
       "legendFormat": "{{pod}}-{{stage}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Updates manager: extend_from_executed_transaction",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 741 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "avg_over_time((avg by (pod, stage) (rate(via_server_state_keeper_updates_manager_extend_from_executed_transaction_sum{pod=~\"$pod|\", namespace=~\"$namespace|\"}[$__rate_interval])/rate(via_server_state_keeper_updates_manager_extend_from_executed_transaction_count{pod=~\"$pod|\", namespace=~\"$namespace|\"}[$__rate_interval])))[$aggr:])\n\n\n\n\n\n\n",
       "legendFormat": "{{pod}}-{{stage}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "batch_executor_command: execute tx",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 749 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "avg_over_time((avg by (pod) (rate(state_keeper_batch_executor_command_response_time_sum{pod=~\"$pod|\", namespace=~\"$namespace|\",command=\"execute_tx\"}[$__rate_interval])/rate(state_keeper_batch_executor_command_response_time_count{pod=~\"$pod|\", namespace=~\"$namespace|\",command=\"execute_tx\"}[$__rate_interval])))[$aggr:])\n",
       "legendFormat": "{{pod}}-{{stage}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "batch_executor_command: finish batch",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 749 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "avg_over_time((avg by (pod) (rate(state_keeper_batch_executor_command_response_time_sum{pod=~\"$pod|\", namespace=~\"$namespace|\",command=\"finish_batch\"}[$__rate_interval])/rate(state_keeper_batch_executor_command_response_time_count{pod=~\"$pod|\", namespace=~\"$namespace|\",command=\"finish_batch\"}[$__rate_interval])))[$aggr:])\n",
       "legendFormat": "{{pod}}-{{stage}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "batch_executor_command: start miniblock",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 749 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "avg_over_time((avg by (pod) (rate(state_keeper_batch_executor_command_response_time_sum{pod=~\"$pod|\", namespace=~\"$namespace|\",command=\"start_next_miniblock\"}[$__rate_interval])/rate(state_keeper_batch_executor_command_response_time_count{pod=~\"$pod|\", namespace=~\"$namespace|\",command=\"start_next_miniblock\"}[$__rate_interval])))[$aggr:])\n",
       "legendFormat": "{{pod}}-{{stage}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Determine seal resolution time",
     "type": "timeseries",
     "description": "The time it takes to determine L1 batch seal resolution after a transaction is executed",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 757 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "avg_over_time((avg by (pod, stage) (rate(via_server_state_keeper_determine_seal_resolution_sum{pod=~\"$pod|\", namespace=~\"$namespace|\"}[$__rate_interval])/rate(via_server_state_keeper_determine_seal_resolution_count{pod=~\"$pod|\", namespace=~\"$namespace|\"}[$__rate_interval])))[$aggr:])\n\n\n\n\n\n\n",
       "legendFormat": "{{pod}}-{{stage}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Match seal resolution time",
     "type": "timeseries",
     "description": "Time it takes to do some actions based on L1 batch seal resolution:\n- for `NoSeal` or `IncludeAndSeal` -- time to fed data into UpdatesManager\n- for others -- time to rollback vm and maybe reject tx ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 757 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "avg_over_time((avg by (pod, stage) (rate(via_server_state_keeper_match_seal_resolution_sum{pod=~\"$pod|\", namespace=~\"$namespace|\"}[$__rate_interval])/rate(via_server_state_keeper_match_seal_resolution_count{pod=~\"$pod|\", namespace=~\"$namespace|\"}[$__rate_interval])))[$aggr:])\n\n\n\n\n\n\n",
       "legendFormat": "{{pod}}-{{stage}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "`process_l1_batch` loop iteration",
     "type": "timeseries",
     "description": "Time of one loop iteration of `process_l1_batch` method",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 765 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "avg_over_time((avg by (pod, stage) (rate(via_server_state_keeper_process_l1_batch_loop_iteration_sum{pod=~\"$pod|\", namespace=~\"$namespace|\"}[$__rate_interval])/rate(via_server_state_keeper_process_l1_batch_loop_iteration_count{pod=~\"$pod|\", namespace=~\"$namespace|\"}[$__rate_interval])))[$aggr:])\n\n\n\n\n\n\n",
       "legendFormat": "{{pod}}-{{stage}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Execute tx time (outer)",
     "type": "timeseries",
     "description": "Time of executing tx. It measures time on keeper side (unlike \"TX vm + storage time\" which measures execution time on batch executor side)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 765 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "avg_over_time((avg by (pod, stage) (rate(via_server_state_keeper_execute_tx_outer_time_sum{pod=~\"$pod|\", namespace=~\"$namespace|\"}[$__rate_interval])/rate(via_server_state_keeper_execute_tx_outer_time_count{pod=~\"$pod|\", namespace=~\"$namespace|\"}[$__rate_interval])))[$aggr:])\n\n\n\n\n\n\n",
       "legendFormat": "{{pod}}-{{stage}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}