{
 "title": "Via - Sequencer",
 "description": "Graphs related to the Via sequencer implementation",
 "tags": [ "via" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Via DA Dispatcher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Blob Dispatch Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(via_server_da_dispatcher_blob_dispatch_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "High latency (p95)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(via_server_da_dispatcher_blob_dispatch_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "Mid latency (p50)"
    }
   ]
  },
  {
   "title": "Proof Dispatch Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(via_server_da_dispatcher_proof_dispatch_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "High latency (p95)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(via_server_da_dispatcher_proof_dispatch_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "Mid latency (p50)"
    }
   ]
  },
  {
   "title": "Inclusion Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(via_server_da_dispatcher_inclusion_latency_bucket[5m])) by (le))",
     "legendFormat": "High latency (p95)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(via_server_da_dispatcher_inclusion_latency_bucket[5m])) by (le))",
     "legendFormat": "Mid latency (p50)"
    }
   ]
  },
  {
   "title": "Blob Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(via_server_da_dispatcher_blob_size_bytes_bucket[5m])) by (le))",
     "legendFormat": "High latency (p95)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(via_server_da_dispatcher_blob_size_bytes_bucket[5m])) by (le))",
     "legendFormat": "Mid latency (p50)"
    }
   ]
  },
  {
   "title": "Dispatch Call Retries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(via_server_da_dispatcher_dispatch_call_retries_bucket[5m])) by (le))",
     "legendFormat": "High latency (p95)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(via_server_da_dispatcher_dispatch_call_retries_bucket[5m])) by (le))",
     "legendFormat": "Mid latency (p50)"
    }
   ]
  },
  {
   "title": "Last Dispatched L1 Batch data",
   "type": "stat",
   "description": "The last dispatched pubdata and proof for an L1 batch number",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(via_server_da_dispatcher_last_dispatched_l1_batch)",
     "legendFormat": "Pubdata"
    },
    {
     "expr": "max(via_server_da_dispatcher_last_dispatched_proof_batch)",
     "legendFormat": "Proof"
    }
   ]
  },
  {
   "title": "Last Included L1 Batch to DA",
   "type": "stat",
   "description": "The last included pubdata or proof for an L1 batch number",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(via_server_da_dispatcher_last_included_l1_batch)",
     "legendFormat": "Pubdata"
    },
    {
     "expr": "max(via_server_da_dispatcher_last_included_proof_batch)",
     "legendFormat": "Proof"
    }
   ]
  },
  { "title": "Via BTC Watch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Processed Inscriptions",
   "type": "timeseries",
   "description": "The btc watch inscriptions processed by the btc watch (Deposit, vote, upgrade...)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "tx" } },
   "targets": [
    {
     "expr": "via_server_btc_watch_inscriptions_processed{stage=\"vote\"}",
     "legendFormat": "Vote"
    },
    {
     "expr": "via_server_btc_watch_inscriptions_processed{stage=\"deposit\"}",
     "legendFormat": "Deposit"
    },
    {
     "expr": "via_server_btc_watch_inscriptions_processed{stage=\"upgrade\"}",
     "legendFormat": "Upgrade"
    }
   ]
  },
  { "title": "Via BTC Sender", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "BTC signer wallet balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    {
     "expr": "via_btc_sender_btc_sender_account_balance / 100000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inscription Confirmation Time",
   "type": "timeseries",
   "description": "The required time for an inscription to get confirmed on chain (for example, 6 after btc blocks).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(via_btc_sender_inscription_confirmation_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "High latency (p95)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(via_btc_sender_inscription_confirmation_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "Mid latency (p50)"
    }
   ]
  },
  {
   "title": "Transaction Broadcast Time",
   "type": "timeseries",
   "description": "The required time to get the transaction in the btc node mempool",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(via_btc_sender_broadcast_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "High latency (p95)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(via_btc_sender_broadcast_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "Mid latency (p50)"
    }
   ]
  },
  {
   "title": "Last Known L1 Blocks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "via_btc_sender_last_known_l1_block{block_number_variant=\"latest\"}",
     "legendFormat": "Sealed"
    },
    {
     "expr": "via_btc_sender_last_known_l1_block{block_number_variant=\"finalized\"}",
     "legendFormat": "Finalized"
    }
   ]
  },
  {
   "title": "Inscriptions In progress",
   "type": "stat",
   "description": "The BTC inscriptions sent to Bitcoin node and are still in progress to be mined or they are stuck (> confirmation time)",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "via_btc_sender_inflight_inscriptions",
     "legendFormat": "Inflight"
    },
    {
     "expr": "via_btc_sender_report_blocked_l1_batch_inscription",
     "legendFormat": "Stuck"
    }
   ]
  }
 ]
}