{
 "title": "Via - verifier",
 "tags": [
  "btc",
  "verifier"
 ],
 "time": { "from": "2025-04-08T23:25:29.515Z", "to": "2025-04-10T07:25:29.515Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Via - BTC sender", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Broadcast Time",
   "type": "timeseries",
   "description": "The required time to broadcast an inscription to Bitcoin network",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "via_verifier_btc_sender_broadcast_time_seconds_sum",
     "legendFormat": "Time"
    }
   ]
  },
  {
   "title": "Number of inscriptions in progress",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "via_verifier_btc_sender_inflight_inscriptions",
     "legendFormat": "Inflight"
    },
    {
     "expr": "via_verifier_btc_sender_report_blocked_l1_batch_inscription",
     "legendFormat": "Stuck"
    }
   ]
  },
  {
   "title": "Inscription Confirmation Time",
   "type": "timeseries",
   "description": "The required time to confirm an inscription in BTC network",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "via_verifier_btc_sender_inscription_confirmation_time_seconds_sum",
     "legendFormat": "Time"
    }
   ]
  },
  {
   "title": "BTC Signer balance ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    {
     "expr": "via_verifier_btc_sender_btc_sender_account_balance / 100000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Known L1 Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "via_verifier_btc_sender_last_known_l1_block{block_number_variant=\"finalized\"}",
     "legendFormat": "Finalized"
    },
    {
     "expr": "via_verifier_btc_sender_last_known_l1_block{block_number_variant=\"voted\"}",
     "legendFormat": "Voted"
    },
    {
     "expr": "via_verifier_btc_sender_last_known_l1_block{block_number_variant=\"indexed\"}",
     "legendFormat": "Indexed"
    },
    {
     "expr": "via_verifier_btc_sender_last_known_l1_block{block_number_variant=\"rejected\"}",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Verifier L1 batch status",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "via_verifier_btc_sender_last_known_l1_block{block_number_variant=\"indexed\"}",
     "legendFormat": "Indexed"
    },
    {
     "expr": "via_verifier_btc_sender_last_known_l1_block{block_number_variant=\"voted\"}",
     "legendFormat": "Voted"
    },
    {
     "expr": "via_verifier_btc_sender_last_known_l1_block{block_number_variant=\"finalized\"}",
     "legendFormat": "Finalized"
    }
   ]
  },
  {
   "title": "Inscriptions Processed Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "via_verifier_btc_watch_inscriptions_processed{stage=\"indexed_l1_batch\"}",
     "legendFormat": "Indexed L1 Batch"
    },
    {
     "expr": "via_verifier_btc_watch_inscriptions_processed{stage=\"deposit\"}",
     "legendFormat": "Deposit"
    },
    {
     "expr": "via_verifier_btc_watch_inscriptions_processed{stage=\"upgrade\"}",
     "legendFormat": "Upgrade"
    },
    {
     "expr": "via_verifier_btc_watch_inscriptions_processed{stage=\"vote\"}",
     "legendFormat": "Vote"
    }
   ]
  },
  { "title": "Via ZK verify", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "ZK verification time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "via_verifier_zk_verification_time_seconds_sum",
     "legendFormat": "Time"
    }
   ]
  },
  {
   "title": "L1 batch status (Valid/Invalid)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "via_verifier_zk_last_valid_l1_batch",
     "legendFormat": "Valid"
    },
    {
     "expr": "via_verifier_zk_last_invalid_l1_batch",
     "legendFormat": "Invalid"
    }
   ]
  },
  { "title": "Via Session", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Musig2 Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "via_verifier_coordinator_session_new{error_type=\"withdrawal\"}",
     "legendFormat": "Withdrawal"
    }
   ]
  },
  {
   "title": "Musig2 Session time execution",
   "type": "timeseries",
   "description": "The required time to execute a session (withdrawal...)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "rate(via_verifier_coordinator_session_time_seconds_sum[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZK verification status for last batch",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "via_verifier_coordinator_session_invalid_message",
     "legendFormat": "Invalid"
    },
    {
     "expr": "via_verifier_coordinator_session_last_valid_session",
     "legendFormat": "Valid"
    }
   ]
  }
 ]
}